export default [
    { servico: 'Corte de Cabelo', preco: 40.00 },
    { servico: 'Corte Disfarçado', preco: 50.00 },
    { servico: 'Barba', preco: 35.00 },
    { servico: 'Corte + Barba', preco: 70.00 },
    { servico: 'Corte + Pintura', preco: 60.00 },
    { servico: 'Corte Navalhado', preco: 55.00 },
    { servico: 'Design de Sobrancelha', preco: 25.00 },
    { servico: 'Coloração', preco: 50.00 },
    { servico: 'Tintura', preco: 45.00 },
    { servico: 'Pacote Deluxe (Corte, Barba, Design de Sobrancelha)', preco: 95.00 },
    { servico: 'Pacote Premium (Corte, Barba, Coloração)', preco: 110.00 },
    { servico: 'Pacote Especial (Corte, Barba, Tintura)', preco: 105.00 },
    { servico: 'Corte de Cabelo Infantil', preco: 25.00 },
    { servico: 'Corte com Tesoura', preco: 45.00 },
    { servico: 'Corte à Máquina', preco: 30.00 },
    { servico: 'Barba Completa', preco: 40.00 },
    { servico: 'Barba Desenhada', preco: 50.00 },
    { servico: 'Barba e Cavanhaque', preco: 45.00 },
    { servico: 'Barba e Bigode', preco: 50.00 },
    { servico: 'Barba e Sobrancelha', preco: 55.00 },
    { servico: 'Barba, Cavanhaque e Bigode', preco: 60.00 },
    { servico: 'Barba, Cavanhaque e Sobrancelha', preco: 65.00 },
    { servico: 'Barba, Bigode e Sobrancelha', preco: 70.00 },
    { servico: 'Barba, Bigode, Cavanhaque e Sobrancelha', preco: 80.00 },
    { servico: 'Barba com Hidratação', preco: 55.00 },
    { servico: 'Barba com Óleo de Barba', preco: 45.00 },
    { servico: 'Barba com Pintura', preco: 60.00 },
    { servico: 'Barba e Tintura de Barba', preco: 65.00 },
    { servico: 'Barba e Tintura de Sobrancelha', preco: 70.00 },
    { servico: 'Barba, Corte de Cabelo e Design de Sobrancelha', preco: 95.00 },
    { servico: 'Barba, Corte de Cabelo e Coloração', preco: 110.00 },
    { servico: 'Barba, Corte de Cabelo e Tintura', preco: 105.00 },
    { servico: 'Corte, Barba e Design de Sobrancelha', preco: 90.00 },
    { servico: 'Corte, Barba e Coloração', preco: 100.00 },
    { servico: 'Corte, Barba e Tintura', preco: 95.00 },
    { servico: 'Corte, Barba, Design de Sobrancelha e Coloração', preco: 115.00 },
    { servico: 'Corte, Barba, Design de Sobrancelha e Tintura', preco: 110.00 },
    { servico: 'Corte, Barba, Coloração e Tintura', preco: 125.00 },
    { servico: 'Corte, Coloração e Tintura', preco: 115.00 },
    { servico: 'Pacote Completo (Corte, Barba, Design de Sobrancelha, Coloração e Tintura)', preco: 150.00 },
    { servico: 'Pacote Premium Plus (Corte, Barba, Design de Sobrancelha, Coloração e Tintura)', preco: 180.00 },
    { servico: 'Corte Militar', preco: 35.00 },
    { servico: 'Corte Moicano', preco: 45.00 },
    { servico: 'Corte Degradê', preco: 55.00 },
    { servico: 'Corte Afro', preco: 50.00 },
    { servico: 'Corte Social', preco: 60.00 },
    { servico: 'Corte Reto', preco: 40.00 },
    { servico: 'Corte Repicado', preco: 45.00 },
    { servico: 'Corte Long Bob', preco: 55.00 },
    { servico: 'Corte Chanel', preco: 50.00 },
    { servico: 'Corte Pixie', preco: 40.00 },
    { servico: 'Corte Undercut', preco: 60.00 },
    { servico: 'Corte Razor Part', preco: 55.00 },
    { servico: 'Corte Pompadour', preco: 50.00 },
    { servico: 'Corte Bowl Cut', preco: 45.00 },
    { servico: 'Corte Shaggy', preco: 55.00 },
    { servico: 'Corte Surfista', preco: 50.00 },
    { servico: 'Corte Skater', preco: 45.00 },
    { servico: 'Corte Bangs', preco: 40.00 },
    { servico: 'Corte Buzz Cut', preco: 35.00 },
    { servico: 'Corte Quiff', preco: 55.00 },
    { servico: 'Corte Assimétrico', preco: 50.00 },
    { servico: 'Corte Rocker', preco: 60.00 },
    { servico: 'Corte Emo', preco: 45.00 },
    { servico: 'Corte Em Camadas', preco: 55.00 },
    { servico: 'Corte Blunt Cut', preco: 50.00 },
    { servico: 'Corte Bob', preco: 40.00 },
    { servico: 'Corte Lob', preco: 45.00 },
    { servico: 'Corte Bowl Cut', preco: 55.00 },
    { servico: 'Corte Fade', preco: 60.00 },
    { servico: 'Corte Taper', preco: 55.00 },
    { servico: 'Corte Undercut', preco: 50.00 },
    { servico: 'Corte Undercut com Desenho', preco: 65.00 },
    { servico: 'Corte Undercut com Textura', preco: 60.00 },
    { servico: 'Corte Undercut com Linhas', preco: 70.00 },
    { servico: 'Corte Undercut com Degradê', preco: 75.00 },
    { servico: 'Corte Undercut com Franja', preco: 55.00 },
    { servico: 'Corte Undercut com Coque Samurai', preco: 80.00 },
    { servico: 'Corte Undercut com Rabo de Cavalo', preco: 65.00 },
    { servico: 'Corte Undercut com Tranças', preco: 75.00 },
    { servico: 'Corte Undercut com Dreads', preco: 70.00 },
    { servico: 'Corte Undercut com Topete', preco: 60.00 },
    { servico: 'Corte Undercut com Moicano', preco: 65.00 },
    { servico: 'Corte Undercut com Textura', preco: 60.00 },
    { servico: 'Corte Undercut com Barba', preco: 85.00 },
    { servico: 'Corte Undercut com Design na Barba', preco: 90.00 },
    { servico: 'Corte Undercut com Pintura', preco: 80.00 },
    { servico: 'Corte Undercut com Tintura', preco: 85.00 },
    { servico: 'Corte Undercut com Mechas', preco: 95.00 },
    { servico: 'Corte Undercut com Luzes', preco: 100.00 },
    { servico: 'Corte Undercut com Californianas', preco: 95.00 },
    { servico: 'Corte Undercut com Ombré Hair', preco: 105.00 },
    { servico: 'Corte Undercut com Balayage', preco: 110.00 },
    { servico: 'Corte Undercut com Ruivo', preco: 95.00 },
    { servico: 'Corte Undercut com Loiro', preco: 100.00 },
    { servico: 'Corte Undercut com Castanho', preco: 95.00 },
    { servico: 'Corte Undercut com Preto', preco: 90.00 },
    { servico: 'Corte Undercut com Coloração Fantasia', preco: 120.00 },
    { servico: 'Corte Undercut com Mechas Coloridas', preco: 115.00 },
    { servico: 'Corte Undercut com Luzes Coloridas', preco: 125.00 },
    { servico: 'Corte Undercut com Corte de Cabelo Infantil', preco: 70.00 },
    { servico: 'Corte Undercut com Corte com Tesoura', preco: 80.00 },
    { servico: 'Corte Undercut com Corte à Máquina', preco: 75.00 },
    { servico: 'Corte Undercut com Barba Completa', preco: 85.00 },
    { servico: 'Corte Undercut com Barba Desenhada', preco: 90.00 },
    { servico: 'Corte Undercut com Barba e Cavanhaque', preco: 85.00 },
    { servico: 'Corte Undercut com Barba e Bigode', preco: 90.00 },
    { servico: 'Corte Undercut com Barba e Sobrancelha', preco: 95.00 },
    { servico: 'Corte Undercut com Barba, Cavanhaque e Bigode', preco: 100.00 },
    { servico: 'Corte Undercut com Barba, Cavanhaque e Sobrancelha', preco: 105.00 },
    { servico: 'Corte Undercut com Barba, Bigode e Sobrancelha', preco: 110.00 },
    { servico: 'Corte Undercut com Barba, Bigode, Cavanhaque e Sobrancelha', preco: 120.00 },
    { servico: 'Corte Undercut com Barba com Hidratação', preco: 105.00 },
    { servico: 'Corte Undercut com Barba com Óleo de Barba', preco: 95.00 },
    { servico: 'Corte Undercut com Barba com Pintura', preco: 110.00 },
    { servico: 'Corte Undercut com Barba e Tintura de Barba', preco: 115.00 },
    { servico: 'Corte Undercut com Barba e Tintura de Sobrancelha', preco: 120.00 },
    { servico: 'Corte Undercut com Barba, Corte de Cabelo e Design de Sobrancelha', preco: 145.00 },
    { servico: 'Corte Undercut com Barba, Corte de Cabelo e Coloração', preco: 160.00 },
    { servico: 'Corte Undercut com Barba, Corte de Cabelo e Tintura', preco: 155.00 },
    { servico: 'Corte Undercut com Corte, Barba e Design de Sobrancelha', preco: 130.00 },
    { servico: 'Corte Undercut com Corte, Barba e Coloração', preco: 140.00 },
    { servico: 'Corte Undercut com Corte, Barba e Tintura', preco: 135.00 },
    { servico: 'Corte Undercut com Corte, Barba, Design de Sobrancelha e Coloração', preco: 155.00 },
    { servico: 'Corte Undercut com Corte, Barba, Design de Sobrancelha e Tintura', preco: 150.00 },
    { servico: 'Corte Undercut com Corte, Barba, Coloração e Tintura', preco: 165.00 },
    { servico: 'Corte Undercut com Corte, Coloração e Tintura', preco: 155.00 },
    { servico: 'Corte Undercut com Pacote Completo (Corte, Barba, Design de Sobrancelha, Coloração e Tintura)', preco: 190.00 },
    { servico: 'Corte Undercut com Pacote Premium Plus (Corte, Barba, Design de Sobrancelha, Coloração e Tintura)', preco: 220.00 },
]

